/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUSS
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    private void combobox() {
        for (Customer z : c.ArrayC) {
            Comboname.addItem(z.getName());
        }
        for (Books x : B.ArrayB) {
            Bcombo.addItem(x.getName());
        }

    }

    public Interface() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        dep = new javax.swing.JTextField();
        Borrow = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        noofbooksavailable = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Name2 = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        CardID = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        CustAdd = new javax.swing.JButton();
        CustDelete = new javax.swing.JButton();
        Custupdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameofc = new javax.swing.JTextField();
        bookname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        OrderAdd = new javax.swing.JButton();
        OrderDelete = new javax.swing.JButton();
        Orderupdate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table3 = new javax.swing.JTable();
        Bcombo = new javax.swing.JComboBox();
        viewO = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table4 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Author = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        bevent = new javax.swing.JTextField();
        EventAdd = new javax.swing.JButton();
        EventDelete = new javax.swing.JButton();
        EventUpdate = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table6 = new javax.swing.JTable();
        bill = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        Comboname = new javax.swing.JComboBox();
        CBupdate = new javax.swing.JCheckBox();
        TotalPrice = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table5 = new javax.swing.JTable();
        Name5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Salary = new javax.swing.JLabel();
        Name10 = new javax.swing.JTextField();
        ID10 = new javax.swing.JTextField();
        Salary10 = new javax.swing.JTextField();
        Department = new javax.swing.JLabel();
        Department10 = new javax.swing.JTextField();
        EmployeeAdd = new javax.swing.JButton();
        EmployeeDelete = new javax.swing.JButton();
        Employeeupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        jLabel1.setText("Name:");

        jLabel2.setText("Author:");

        jLabel3.setText("Department");

        jLabel4.setText("Borrow:");

        name.setText("Enter Name");

        author.setText("Enter Author");

        dep.setText("Enter Dep");

        Borrow.setText("Borrowed or not");
        Borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel15.setText("noofbooksavailable");

        noofbooksavailable.setText("1");

        jLabel17.setText("Price");

        price.setText("2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(author))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Borrow))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dep))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price)
                            .addComponent(noofbooksavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Borrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(noofbooksavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add)
                    .addComponent(update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Books", jPanel1);

        Name2.setText("Enter Name");

        PhoneNumber.setText("Enter PhoneNumber");
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });

        CardID.setText("Enter CardID");

        Email.setText("Enter Email");
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        CustAdd.setText("Add");
        CustAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustAddActionPerformed(evt);
            }
        });

        CustDelete.setText("Delete");
        CustDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustDeleteActionPerformed(evt);
            }
        });

        Custupdate.setText("update");
        Custupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustupdateActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");

        jLabel6.setText("PhoneNumber");

        jLabel7.setText("CardID");

        jLabel8.setText("Email");

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Table2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CustAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(Custupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Name2)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(CardID)
                    .addComponent(Email))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CardID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustAdd)
                            .addComponent(CustDelete)
                            .addComponent(Custupdate))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Customer", jPanel2);

        jLabel9.setText("Name Of Customer");

        jLabel10.setText("Book Name");

        jLabel11.setText("Address");

        nameofc.setText("Enter cust name");

        bookname.setText("Enter book name");

        address.setText("Enter cust address");

        OrderAdd.setText("Add");
        OrderAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderAddActionPerformed(evt);
            }
        });

        OrderDelete.setText("Delete");
        OrderDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDeleteActionPerformed(evt);
            }
        });

        Orderupdate.setText("Update");
        Orderupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderupdateActionPerformed(evt);
            }
        });

        Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(Table3);

        viewO.setText("View");
        viewO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(viewO))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address)
                    .addComponent(bookname)
                    .addComponent(nameofc)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(OrderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Orderupdate, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nameofc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Bcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrderAdd)
                            .addComponent(OrderDelete)
                            .addComponent(Orderupdate)
                            .addComponent(viewO))
                        .addGap(18, 18, 18)
                        .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order", jPanel4);

        Table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(Table4);

        jLabel12.setText("Author");

        jLabel13.setText("Date");

        jLabel14.setText("bevent");

        Author.setText("Enter name of author");

        Date.setText("Enter date of event");

        bevent.setText("Enter book discussed name ");

        EventAdd.setText("Add");
        EventAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventAddActionPerformed(evt);
            }
        });

        EventDelete.setText("Delete");
        EventDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventDeleteActionPerformed(evt);
            }
        });

        EventUpdate.setText("Update");
        EventUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(32, 32, 32)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Date)
                            .addComponent(Author, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bevent, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(EventAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(EventUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EventDelete)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(bevent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventAdd)
                    .addComponent(EventDelete)
                    .addComponent(EventUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Events", jPanel5);

        Table6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table6.setUpdateSelectionOnSort(false);
        Table6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table6MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Table6);

        bill.setEditable(false);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(pTable);

        CBupdate.setText("Update");

        TotalPrice.setText("Total Price");
        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comboname, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(CBupdate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(TotalPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(view)
                            .addComponent(delete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Comboname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TotalPrice)))
                            .addComponent(CBupdate))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Purchase", jPanel7);

        Table5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(Table5);

        Name5.setText("Name");

        jLabel16.setText("ID");

        Salary.setText("Salary");

        Name10.setText("Enter Employee name");

        ID10.setText("Enter Employee ID");

        Salary10.setText("Enter Employee Salary");

        Department.setText("Department");

        Department10.setText("Enter depart where emp work in");

        EmployeeAdd.setText("Add");
        EmployeeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeAddActionPerformed(evt);
            }
        });

        EmployeeDelete.setText("Delete");
        EmployeeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeDeleteActionPerformed(evt);
            }
        });

        Employeeupdate.setText("Update");
        Employeeupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name5)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name10)
                            .addComponent(ID10)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Department)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Salary10))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(EmployeeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Employeeupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(EmployeeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 22, Short.MAX_VALUE))
                                    .addComponent(Department10)))))
                    .addComponent(Salary))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ID10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salary)
                    .addComponent(Salary10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department)
                    .addComponent(Department10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeAdd)
                    .addComponent(EmployeeDelete)
                    .addComponent(Employeeupdate))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Employee", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrowActionPerformed
    Books B = new Books();
    DefaultTableModel TB = new DefaultTableModel();
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        try {
            int Number = Integer.parseInt(noofbooksavailable.getText());
            float Price = Float.parseFloat(price.getText());
            String Name = name.getText();
            String Author = author.getText();
            String Department = dep.getText();
            String borrow = Borrow.getText();
            B.addbook(Name, Author, Department, borrow, Price, Number);
            DefaultTableModel x = new Books().getData();
            for (Books z : B.ArrayB) {
                x.addRow(new String[]{z.getName(), z.getAuthor(), z.getDepartment(), z.getBorrow(), Float.toString(z.getPrice()), Integer.toString(z.getNobooks())});
            }

            Table.setModel(x);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter correct Price and No Of Books");
        }

    }//GEN-LAST:event_AddActionPerformed
    private float SUM() {
        int row = pTable.getRowCount();
        float sum = 0;
        for (int i = 0; i < row; i++) {
            sum = sum + Float.parseFloat(pTable.getValueAt(i, 2).toString());
        }

        return sum;
    }

    public void BOOKPRINT() {
        DefaultTableModel x = new Books().getData();
        for (Books z : B.ArrayB) {
            x.addRow(new String[]{z.getName(), z.getAuthor(), z.getDepartment(), z.getBorrow(), Float.toString(z.getPrice()), Integer.toString(z.getNobooks())});
        }
        Table.setModel(x);
    }
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int i = Table.getSelectedRow();
        int Number = Integer.parseInt(noofbooksavailable.getText());
        float Price = Float.parseFloat(price.getText());
        String Name = name.getText();
        String Author = author.getText();
        String Department = dep.getText();
        String borrow = Borrow.getText();
        B.update(i, Name, Author, Department, borrow, Price, Number);
        DefaultTableModel x = new Books().getData();
        for (Books z : B.ArrayB) {
            x.addRow(new String[]{z.getName(), z.getAuthor(), z.getDepartment(), z.getBorrow(), Float.toString(z.getPrice()), Integer.toString(z.getNobooks())});
        }

        Table.setModel(x);

    }//GEN-LAST:event_updateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int i = Table.getSelectedRow();

        B.delete(i);
        DefaultTableModel x = new Books().getData();
        for (Books z : B.ArrayB) {
            x.addRow(new String[]{z.getName(), z.getAuthor(), z.getDepartment(), z.getBorrow(), Float.toString(z.getPrice()), Integer.toString(z.getNobooks())});
        }

        Table.setModel(x);
    }//GEN-LAST:event_DeleteActionPerformed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed
    Customer c = new Customer();
    private void CustAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustAddActionPerformed
        // TODO add your handling code here:
        String Name = Name2.getText();
        String Phonenumber = PhoneNumber.getText();
        String Cardid = CardID.getText();
        String email = Email.getText();
        c.add(Name, Phonenumber, Cardid, email);
        DefaultTableModel x = new Customer().getData();
        for (Customer z : c.ArrayC) {
            x.addRow(new String[]{z.getName(), z.getPhonenumber(), z.getCardID(), z.getEmail()});
        }

        Table2.setModel(x);
    }//GEN-LAST:event_CustAddActionPerformed

    private void CustDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustDeleteActionPerformed
        // TODO add your handling code here:
        int i = Table2.getSelectedRow();

        c.delete(i);
        DefaultTableModel x = new Customer().getData();
        for (Customer z : c.ArrayC) {
            x.addRow(new String[]{z.getName(), z.getPhonenumber(), z.getCardID(), z.getEmail()});
        }

        Table2.setModel(x);

    }//GEN-LAST:event_CustDeleteActionPerformed

    private void CustupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustupdateActionPerformed
        // TODO add your handling code here:
        int i = Table2.getSelectedRow();
        String Name = Name2.getText();
        String Phonenumber = PhoneNumber.getText();
        String Cardid = CardID.getText();
        String email = Email.getText();
        c.update(i, Name, Phonenumber, Cardid, email);
        DefaultTableModel x = new Customer().getData();
        for (Customer z : c.ArrayC) {
            x.addRow(new String[]{z.getName(), z.getPhonenumber(), z.getCardID(), z.getEmail()});
        }

        Table2.setModel(x);
    }//GEN-LAST:event_CustupdateActionPerformed
    Order O = new Order();
    private void OrderAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderAddActionPerformed
        // TODO add your handling code here:

        String Bookname = Bcombo.getSelectedItem().toString();
        String department = Table.getValueAt(Bcombo.getSelectedIndex(), 2).toString();
        String author = Table.getValueAt(Bcombo.getSelectedIndex(), 1).toString();
        String Borrowed = Table.getValueAt(Bcombo.getSelectedIndex(), 3).toString();
        int nooofbooks = Integer.parseInt(Table.getValueAt(Bcombo.getSelectedIndex(), 5).toString());
        float Price = Float.parseFloat(Table.getValueAt(Bcombo.getSelectedIndex(), 4).toString());

        String Nameofc = nameofc.getText();

        String Address = address.getText();

        if (nooofbooks <= 0) {
            nooofbooks = 0;
        } else {
            O.addorder(Nameofc, Bookname, Address);
            nooofbooks = nooofbooks - 1;
        }
        int index = Bcombo.getSelectedIndex();

        B.update(index, Bookname, author, department, Borrowed, Price, nooofbooks);

        DefaultTableModel x = new Order().getData();
        for (Order z : O.ArrayO) {
            x.addRow(new String[]{z.getNameofc(), z.getBookname(), z.getAddress()});
        }
        BOOKPRINT();
        Table3.setModel(x);
    }//GEN-LAST:event_OrderAddActionPerformed

    private void OrderDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDeleteActionPerformed
        // TODO add your handling code here:
        int i = Table3.getSelectedRow();

        O.delete(i);
        DefaultTableModel x = new Order().getData();
        for (Order z : O.ArrayO) {
            x.addRow(new String[]{z.getNameofc(), z.getBookname(), z.getAddress()});
        }

        Table3.setModel(x);
    }//GEN-LAST:event_OrderDeleteActionPerformed

    private void OrderupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderupdateActionPerformed
        // TODO add your handling code here:
        int i = Table3.getSelectedRow();
        String Nameofc = nameofc.getText();
        String Bookname = Bcombo.getSelectedItem().toString();
        String Address = address.getText();

        O.update(i, Nameofc, Bookname, Address);
        DefaultTableModel x = new Order().getData();
        for (Order z : O.ArrayO) {
            x.addRow(new String[]{z.getNameofc(), z.getBookname(), z.getAddress()});
        }

        Table3.setModel(x);
    }//GEN-LAST:event_OrderupdateActionPerformed
    Events E = new Events();
    private void EventAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventAddActionPerformed
        // TODO add your handling code here:
        String A = Author.getText();
        String date = Date.getText();
        String Bevent = bevent.getText();

        E.addEvent(A, date, Bevent);
        DefaultTableModel x = new Events().getData();
        for (Events z : E.ArrayE) {
            x.addRow(new String[]{z.getauthor(), z.getdate(), z.getbevent()});

        }
        Table4.setModel(x);
    }//GEN-LAST:event_EventAddActionPerformed

    private void EventDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventDeleteActionPerformed
        // TODO add your handling code here:
        int i = Table4.getSelectedRow();

        E.delete(i);
        DefaultTableModel x = new Events().getData();
        for (Events z : E.ArrayE) {
            x.addRow(new String[]{z.getauthor(), z.getdate(), z.getbevent()});
        }

        Table4.setModel(x);
    }//GEN-LAST:event_EventDeleteActionPerformed

    private void EventUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventUpdateActionPerformed
        // TODO add your handling code here:
        int i = Table4.getSelectedRow();
        String A = Author.getText();
        String date = Date.getText();
        String Bevent = bevent.getText();

        E.update(i, A, date, Bevent);
        DefaultTableModel x = new Events().getData();
        for (Events z : E.ArrayE) {
            x.addRow(new String[]{z.getauthor(), z.getdate(), z.getbevent()});
        }

        Table4.setModel(x);
    }//GEN-LAST:event_EventUpdateActionPerformed

    private void EmployeeupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeupdateActionPerformed
        // TODO add your handling code here:

        int i = Table5.getSelectedRow();
        String Name = Name10.getText();
        String id = ID10.getText();
        String salary = Salary10.getText();
        String department = Department10.getText();

        Emp.update(i, Name, id, salary, department);
        DefaultTableModel x = new Employee().getData();
        for (Employee z : Emp.ArrayEmp) {
            x.addRow(new String[]{z.getName(), z.getID(), z.getSalary(), z.getDepartment()});

        }
        Table5.setModel(x);
    }//GEN-LAST:event_EmployeeupdateActionPerformed

    private void EmployeeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeDeleteActionPerformed
        // TODO add your handling code here:
        int i = Table5.getSelectedRow();

        Emp.delete(i);
        DefaultTableModel x = new Employee().getData();
        for (Employee z : Emp.ArrayEmp) {
            x.addRow(new String[]{z.getName(), z.getID(), z.getSalary(), z.getDepartment()});
        }

        Table5.setModel(x);

    }//GEN-LAST:event_EmployeeDeleteActionPerformed

    private void EmployeeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeAddActionPerformed
        // TODO add your handling code here:
        String Name = Name10.getText();
        String id = ID10.getText();
        String salary = Salary10.getText();
        String department = Department10.getText();
        Emp.add(Name, id, salary, department);
        DefaultTableModel x = new Employee().getData();
        for (Employee z : Emp.ArrayEmp) {
            x.addRow(new String[]{z.getName(), z.getID(), z.getSalary(), z.getDepartment()});
        }

        Table5.setModel(x);

    }//GEN-LAST:event_EmployeeAddActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int i = pTable.getSelectedRow();
        Pur.delete(i);
        DefaultTableModel x = new Purchase().getData();
        printpurchase();
    }//GEN-LAST:event_deleteActionPerformed
    Purchase Pur = new Purchase();
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel x = new Books().getData2();
        DefaultTableModel TAB = new Purchase().getData();
        combobox();
        for (Books z : B.ArrayB) {
            x.addRow(new String[]{z.getName(), Float.toString(z.getPrice()), Integer.toString(z.getNobooks())});
        }
        for (Purchase q : Pur.P) {
            TAB.addRow(new String[]{q.getNameofCust(), q.getNameofbook(), Integer.toString(q.getNoofbooksavailable()), Float.toString(q.getPrice())});
        }
        pTable.setModel(TAB);
        Table6.setModel(x);
    }//GEN-LAST:event_viewActionPerformed
    private void printpurchase() {
        DefaultTableModel a = new Books().getData2();

        DefaultTableModel x = new Purchase().getData();
        for (Books z : B.ArrayB) {
            a.addRow(new String[]{z.getName(), Float.toString(z.getPrice()), Integer.toString(z.getNobooks())});
        }
        for (Purchase w : Pur.P) {
            x.addRow(new String[]{w.getNameofCust(), w.getNameofbook(), Float.toString(w.getPrice())});
        }
        Table6.setModel(a);
        pTable.setModel(x);
    }
    private void Table6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table6MouseClicked
        // TODO add your handling code here:
        String customername = Comboname.getSelectedItem().toString();
        String nameofbook = Table6.getValueAt(Table6.getSelectedRow(), 0).toString();
        String department = Table.getValueAt(Table6.getSelectedRow(), 2).toString();
        String Author = Table.getValueAt(Table6.getSelectedRow(), 1).toString();
        String Borrowed = Table.getValueAt(Table6.getSelectedRow(), 3).toString();
        int nooofbooks = Integer.parseInt(Table.getValueAt(Table6.getSelectedRow(), 5).toString());
        float Price = Float.parseFloat(Table6.getValueAt(Table6.getSelectedRow(), 1).toString());
        if (CBupdate.isSelected()) {
            int i = pTable.getSelectedRow();
            Pur.updateP(i, nameofbook, nameofbook, Price);
            printpurchase();

        } else {
            int index = Table6.getSelectedRow();
            if (nooofbooks <= 0) {
                nooofbooks = 0;
            } else {
                Pur.addP(customername, nameofbook, Price);
                nooofbooks = nooofbooks - 1;
            }

            B.update(index, nameofbook, Author, department, Borrowed, Price, nooofbooks);
            printpurchase();
            BOOKPRINT();

        }
    }//GEN-LAST:event_Table6MouseClicked

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
        bill.setText(Float.toString(SUM()));
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void viewOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOActionPerformed
        // TODO add your handling code here:
        combobox();
        viewO.setVisible(false);
    }//GEN-LAST:event_viewOActionPerformed
    Employee Emp = new Employee();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Author;
    private javax.swing.JComboBox Bcombo;
    private javax.swing.JTextField Borrow;
    private javax.swing.JCheckBox CBupdate;
    private javax.swing.JTextField CardID;
    private javax.swing.JComboBox Comboname;
    private javax.swing.JButton CustAdd;
    private javax.swing.JButton CustDelete;
    private javax.swing.JButton Custupdate;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Department;
    private javax.swing.JTextField Department10;
    private javax.swing.JTextField Email;
    private javax.swing.JButton EmployeeAdd;
    private javax.swing.JButton EmployeeDelete;
    private javax.swing.JButton Employeeupdate;
    private javax.swing.JButton EventAdd;
    private javax.swing.JButton EventDelete;
    private javax.swing.JButton EventUpdate;
    private javax.swing.JTextField ID10;
    private javax.swing.JTextField Name10;
    private javax.swing.JTextField Name2;
    private javax.swing.JLabel Name5;
    private javax.swing.JButton OrderAdd;
    private javax.swing.JButton OrderDelete;
    private javax.swing.JButton Orderupdate;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JLabel Salary;
    private javax.swing.JTextField Salary10;
    private javax.swing.JTable Table;
    private javax.swing.JTable Table2;
    private javax.swing.JTable Table3;
    private javax.swing.JTable Table4;
    private javax.swing.JTable Table5;
    private javax.swing.JTable Table6;
    private javax.swing.JButton TotalPrice;
    private javax.swing.JTextField address;
    private javax.swing.JTextField author;
    private javax.swing.JTextField bevent;
    private javax.swing.JTextField bill;
    private javax.swing.JTextField bookname;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nameofc;
    private javax.swing.JTextField noofbooksavailable;
    private javax.swing.JTable pTable;
    private javax.swing.JTextField price;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    private javax.swing.JButton viewO;
    // End of variables declaration//GEN-END:variables
}
